CREATE TABLE IF NOT EXISTS "Account" (
	"id" INTEGER NOT NULL, "accountid" CHAR(50) NOT NULL, "password" CHAR(50) NOT NULL, "authority" CHAR(20) NOT NULL,
	PRIMARY KEY ("id"),
	CONSTRAINT "UK_accountID" UNIQUE ("accountid")
);

CREATE TABLE IF NOT EXISTS "Comment" (
	"id" INTEGER NOT NULL,
	"content" TEXT NOT NULL DEFAULT '',
	"created_date" DATETIME NOT NULL DEFAULT '',
	"writer" INTEGER NOT NULL,
	"issue_id" INTEGER NOT NULL,
	PRIMARY KEY ("id"),
	CONSTRAINT "FK__Account_to_Comment" FOREIGN KEY ("writer") REFERENCES "Account" ("id") ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT "FK__Issue" FOREIGN KEY ("issue_id") REFERENCES "Issue" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Issue" (
	"id" INTEGER NOT NULL,
	"title" VARCHAR(200) NOT NULL DEFAULT '',
	"description" TEXT NOT NULL DEFAULT '',
	"reportedDate" DATETIME NOT NULL DEFAULT '',
	"priority" VARCHAR(20) NOT NULL DEFAULT '',
	"state" VARCHAR(20) NOT NULL DEFAULT '',
	"project_id" INTEGER NULL DEFAULT NULL,
	"reporter" INTEGER NULL DEFAULT NULL,
	"assignee" INTEGER NULL DEFAULT NULL,
	"fixer" INTEGER NULL DEFAULT NULL,
	PRIMARY KEY ("id"),
	CONSTRAINT "FK_Project_to_Issue" FOREIGN KEY ("project_id") REFERENCES "Project" ("id") ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT "FK_Reporter_to_Issue" FOREIGN KEY ("reporter") REFERENCES "Account" ("id") ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT "FK_Assignee_to_Issue" FOREIGN KEY ("assignee") REFERENCES "Account" ("id") ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT "FK_Fixer_to_Issue" FOREIGN KEY ("fixer") REFERENCES "Account" ("id") ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "Project" (
	"id" INTEGER NOT NULL, "name" VARCHAR(200) NOT NULL, "created_date" DATETIME NULL,
	PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "ProjectJoin" (
	"id" INTEGER NOT NULL,
	"project_id" INTEGER NOT NULL,
	"account_id" INTEGER NOT NULL,
	PRIMARY KEY ("id"),
	CONSTRAINT "FK__Project_to_ProjecJjoin" FOREIGN KEY ("project_id") REFERENCES "Project" ("id") ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT "FK__Account_to_ProjecJjoin" FOREIGN KEY ("account_id") REFERENCES "Account" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);